- name: apache2_inatall
  apt:
    name: apache2
    state: present

- file:
    path: /var/www/html/index.html
    state: absent

- name: deploy_code
  copy:
     src: /home/agent/ansible/roles/apache/files/source-code/index.html
     dest: /var/www/html/
- name: deploy_code
  template:
       src: /home/agent/ansible/roles/apache/templates/hello.html.j2
       dest: /var/www/html/
- name: pakg
  apt:
    name: "{{packg_cmd}}"
    state: present
  notify:
  - restart_apache2
